### PR TITLE
Migrate getBNBData to PHP, rename to getBNBData.php and update Docker…

### PR DESCRIPTION
**Pull request by jmechnich**
…file and documentation

Addresses #161 .

### CODE REVIEW

**Comment by jmechnich** [comment]
@mahaesin could you please cross-check the validity of the Dockerfile and documentation? Thanks!

**Comment by mahaesin** [comment]
- Container build and start up successful
- BNBData ist successfully fetched
- malibu/bnb/recherche.php contains inlined deprecation warning

`Deprecated: usort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /var/www/html/malibu/bnb/recherche.php on line 217`

- search result seems valid

**Comment by jmechnich** [comment]
The deprecation warning can be taken care of separately. Thanks @mahaesin !

**Comment by zuphilip** [comment]
Thank you very much @jmechnich for the work and  @mahaesin for checking it! 💯

**Pull request merged**
