### PR TITLE
Add Dockerfile-dev for developing

### PR DESCRIPTION
**Pull request by zuphilip**

### CODE REVIEW

**Comment by zuphilip** [comment]
This looks to partially overlap with the [Makefile](https://github.com/UB-Mannheim/malibu/blob/master/dist/Makefile) but I am confused how the Makefile is working. 

`make` seems not working at all on Windows inside Docker or Git Bash... @kba Any help is appreciated.

**Comment by kba** [comment]
The Makefile is just a thin layer for not having to spell out the docker commands (e.g. `make docker` to build the image) or . For it to work, you need some form of make which isn't available on Windows apparently.

**Comment by zuphilip** [comment]
Okay. Is the workflow with `make` then, that every time I changed some files I have to stop the old container, build it again and run it again? If yes, I think the `Dockerfile-dev` in this PR might be an overall improvement. Would you agree?

**Comment by kba** [comment]
Dockerfile-dev is not downloading the data or copying files into the container? Just setting up apache and yaz? Couldn't you mount the current working directory into the normal container and have the same effect?

**Comment by zuphilip** [comment]
> Dockerfile-dev is not downloading the data or copying files into the container? Just setting up apache and yaz?

Yes, it is an attempt replace the need for XAMPP.

> Couldn't you mount the current working directory into the normal container and have the same effect?

Yes, that sounds right... Maybe another directory name is needed then, e.g.
```
docker run -d -p 12345:80 -v `pwd`:/var/www/html/malibu-dev <NORMAL MALIBU CONTAINER>
```

**Pull request closed without merging**
